version: '3.9'
services:
  postgres2:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "123ekfy"
      PGDATA: /data/postgres
    ports:
      - "5432:5432"
